Several fixes
Several fixes

diff --git a/packaging/Windows/defs/managed-components b/packaging/Windows/defs/managed-components
--- a/packaging/Windows/defs/managed-components
+++ b/packaging/Windows/defs/managed-components
@@ -1,5 +1,6 @@
 #!/bin/bash -xe
 
+REPO=${2:-"https://download.mono-project.com/archive/nightly/macos-10-universal/MonoFramework-MDK-5.7.0.134.macos10.xamarin.universal.pkg"}
 REPODIR=$(dirname $(realpath $0))/../repos/managed-components
 
 error()
@@ -17,13 +18,13 @@ download()
 {
 	mkdir -p ${REPODIR}
 	report "Downloading Xar"
-	wget --quiet -O ${REPODIR}/xar.tar.gz https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/xar/xar-1.5.2.tar.gz || error "*** Could not download Xar ***"
+	wget --quiet -O ${REPODIR}/xar.tar.gz https://f001.backblazeb2.com/file/nanobot/xar-2.0.0.tar.gz || error "*** Could not download Xar ***"
 	report "Downloading x64 hostfxr.dll"
 	wget --quiet -O ${REPODIR}/hostfxr-x64.zip https://www.nuget.org/api/v2/package/runtime.win-x64.Microsoft.NETCore.DotNetHostResolver/2.0.0-preview2-25407-01 || error "*** Could not download 64bit hostfxr.dll ***"
 	report "Downloading x86 hostfxr.dll"
 	wget --quiet -O ${REPODIR}/hostfxr-x86.zip https://www.nuget.org/api/v2/package/runtime.win-x86.Microsoft.NETCore.DotNetHostResolver/2.0.0-preview2-25407-01 || error "*** Could not download 32bit hostfxr.dll ***"
 	report "Copying Mono MDK for Mac"
-	cp $1 ${REPODIR}/mono.xar
+	wget --quiet -O ${REPODIR}/mono.xar ${REPO}
 }
 
 clean()
@@ -50,7 +51,10 @@ build()
 		mkdir -p xar
 		tar xf xar.tar.gz -C xar/ --strip-components=1
 		pushd xar/
-		./configure
+		./autogen.sh
+		cd xar
+		./configure --host=i686-pc-cygwin --enable-static --disable-shared --without-bzlib
+		make clean
 		make
 		popd
 	fi
@@ -61,7 +65,7 @@ build()
 	mkdir -p hostfxr-x86
 	unzip -j "${REPODIR}/hostfxr-x86.zip" "runtimes/win-x86/native/hostfxr.dll" -d "hostfxr-x86"
 	report "Unpacking Mono for Mac"
-	xar/src/xar -x -f mono.xar
+	xar/xar/src/xar.exe -x -f mono.xar
 	zcat mono.pkg/Payload | bsdcpio -i
 	mv Library/Frameworks/Mono.framework/Versions/5.* mono-mac
 	popd
@@ -126,18 +130,31 @@ install()
 		sed -i 's#/Library.*mono #\"\$\{BASH_SOURCE%/\*\}\"/mono #' $i
 		sed -i 's#/Library.*cli #\"\$\{BASH_SOURCE%/\*\}\"/cli #' $i
 		if [ -n "$(grep -hoE '[\" ]/Library.*\.(exe|dll)' $i)" ]
-			then EXENAME=$(basename `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i | sed 's/^\"//'`)
-			RUNTIME=$(dirname `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i` | sed 's/^\"//' | sed 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/##' | sed '/^mono\//! s#^#..\\\\#' | sed 's#^mono/##')
+			then EXENAME=$(basename `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i | sed 's/"//g' | sed 's/$MONO_OPTIONS//g' | sed 's/.*[[:space:]]//'`)
+			RUNTIME=$(dirname `grep -hoE -m 1 '[\" ]/Library.*\.(exe|dll)' $i | sed 's/$MONO_OPTIONS//g'` | sed 's/^\"//' | sed 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/##' | sed '/^mono\//! s#^#..\\\\#' | sed 's#^mono/##' | sed '$!d')
 			sed "s#@@RUNTIME@@#${RUNTIME}\\\\#g" ${REPODIR}/../../resources/wrapper.bat > $i.bat
 			sed -i "s#@@COMMAND@@#${EXENAME}#g" $i.bat
 			sed -i 's#/#\\#g' $i.bat
+			sed -i 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/#\"\$\(cygpath -w \"\$\{BASH_SOURCE%/\*\}\"/../lib/\)\"#g#' $i
+			sed -i 's#\"\"#\"#g' $i
+			sed -i 's#)\"#)#g' $i
+			sed -i 's#exe #exe\" #' $i
+			sed -i 's#dll #dll\" #' $i
+			sed -i 's#basename \$0#basename \"\$0\"#' $i
 		fi
-		sed -i 's#/Library.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/#\"\$\(cygpath -w \"\$\{BASH_SOURCE%/\*\}\"/../lib/\)\"#g#' $i
-		sed -i 's#\"\"#\"#g' $i
-		sed -i 's#)\"#)#g' $i
-		sed -i 's#exe #exe\" #' $i
-		sed -i 's#dll #dll\" #' $i
-		sed -i 's#basename \$0#basename \"\$0\"#' $i
+		if [ -n "$(grep -hoE '[\" ]/Users.*\.(exe|dll)' $i)" ]
+			then EXENAME=$(basename `grep -hoE -m 1 '[\" ]/Users.*\.(exe|dll)' $i | sed 's/"//g' | sed 's/$MONO_OPTIONS//g' | sed 's/.*[[:space:]]//'`)
+			RUNTIME=$(dirname `grep -hoE -m 1 '[\" ]/Users.*\.(exe|dll)' $i | sed 's/$MONO_OPTIONS//g'` | sed 's/^\"//' | sed 's#/Users.*/lib/##' | sed '/^mono\//! s#^#..\\\\#' | sed 's#^mono/##' | sed '$!d')
+			sed "s#@@RUNTIME@@#${RUNTIME}\\\\#g" ${REPODIR}/../../resources/wrapper.bat > $i.bat
+			sed -i "s#@@COMMAND@@#${EXENAME}#g" $i.bat
+			sed -i 's#/#\\#g' $i.bat
+			sed -i 's#/Users.*/[0-9]\+\.[0-9]\+\.[0-9]\+/lib/#\"\$\(cygpath -w \"\$\{BASH_SOURCE%/\*\}\"/../lib/\)\"#g#' $i
+			sed -i 's#\"\"#\"#g' $i
+			sed -i 's#)\"#)#g' $i
+			sed -i 's#exe #exe\" #' $i
+			sed -i 's#dll #dll\" #' $i
+			sed -i 's#basename \$0#basename \"\$0\"#' $i
+		fi
 	done
 	cp xsp4 xsp
 	cp xsp4.bat xsp.bat
